### PR TITLE
GP-8788 Add BankingPluginInstance import API

### PR DESCRIPTION
**Pull request by pfigel**

### CODE REVIEW

**Comment by bjendres** [comment]
sweet :)

**Comment by bjendres** [comment]
Looks good! Is it working in production? Would you mind making a PR to the main repository? If not, would you mind if I did?

**Comment by pfigel** [comment]
@bjendres we're deploying this tomorrow, but it's been tested fairly extensively, so it's probably good to go. I've opened a PR here: https://github.com/Project60/org.project60.banking/pull/426

**Comment by bjendres** [comment]
> @bjendres we're deploying this tomorrow, but it's been tested fairly extensively, so it's probably good to go. I've opened a PR here: [Project60#426](https://github.com/Project60/org.project60.banking/pull/426)

Thank you!

**Pull request merged**
